### ISSUE TITLE
Unit Selection

### ISSUE THREAD

**Issue by martindevans** [CylonSB/bounded-planet#3]
Originally encompassed proper unit movement, but has been rebranded to _just_ unit selection, in favour of #50 being real movement.

**Comment by martindevans** [comment]
@Jerald afaik picking is done, but what's the plan with the remaining stuff from this issue? Bump it up to MVP#2?

**Comment by martindevans** [comment]
Currently blocked on Bevy 0.2

**Comment by Jerald** [comment]
I'm rebranding this issue to _just_ unit selection. We also have #50 which is inexplicably the same thing, so that one can be for the more proper movement itself.
