### ISSUE TITLE
Investigate UI

### ISSUE THREAD

**Issue by martindevans** [CylonSB/bounded-planet#32]
- [ ] Show UI elements
 - [ ] Capture some kind of input event (e.g. button click)
 - [ ] Take some action (e.g. toggle visibility of text label when button is clicked)
 - [ ] Extension: work with Nyefari on scene transitions to have a scene transition between 2 menus, triggerd by button click.

Investigate:
https://crates.io/crates/iced
https://crates.io/crates/druid

**Comment by martindevans** [comment]
https://github.com/Gekkio/imgui-rs
https://github.com/PistonDevelopers/conrod
https://crates.io/crates/iui
https://github.com/linebender/druid
https://github.com/rust-native-ui/libui-rs

metalist: https://arewegameyet.rs/ecosystem/ui/

**Comment by Jerald** [comment]
https://raphlinus.github.io/rust/druid/2020/09/25/principled-reactive-ui.html

**Comment by martindevans** [comment]
https://github.com/emilk/egui

**Comment by Jerald** [comment]
The current scope of my work on this issue is to integrate `egui` with bevy so it can render.
